config/routes.rb
Rails.application.routes.draw do
  resources :notices
  devise_for :users
  resources :users
  resources :stores
  resources :packages
  resources :champions
  resources :skins
  resources :chromas

  get '/dashboard', to: 'pages#dashboard'
  get '/perfil', to: 'pages#perfil'
  get '/colecao', to: 'pages#colecao'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_one_attached :image
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:image, :title, :url)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.url %></td>
        <td><%= image_tag notice.image %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @notice.url %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @notice.image %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>