config/routes.rb
Rails.application.routes.draw do
  resources :notices
  devise_for :users
  resources :users
  resources :stores
  resources :packages
  resources :champions
  resources :skins
  resources :chromas

  get '/dashboard', to: 'pages#dashboard'
  get '/perfil', to: 'pages#perfil'
  get '/colecao', to: 'pages#colecao'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :package
  belongs_to :champion
  belongs_to :skin
  belongs_to :chroma
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:package_id, :champion_id, :skin_id, :chroma_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :package_id %>
    <%= form.text_field :package_id %>
  </div>

  <div class="field">
    <%= form.label :champion_id %>
    <%= form.text_field :champion_id %>
  </div>

  <div class="field">
    <%= form.label :skin_id %>
    <%= form.text_field :skin_id %>
  </div>

  <div class="field">
    <%= form.label :chroma_id %>
    <%= form.text_field :chroma_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>Champion</th>
      <th>Skin</th>
      <th>Chroma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.package %></td>
        <td><%= store.champion %></td>
        <td><%= store.skin %></td>
        <td><%= store.chroma %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Package:</strong>
  <%= @store.package %>
</p>

<p>
  <strong>Champion:</strong>
  <%= @store.champion %>
</p>

<p>
  <strong>Skin:</strong>
  <%= @store.skin %>
</p>

<p>
  <strong>Chroma:</strong>
  <%= @store.chroma %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>