config/routes.rb
Rails.application.routes.draw do
  resources :notices
  devise_for :users
  resources :users
  resources :stores
  resources :packages
  resources :champions
  resources :skins
  resources :chromas

  get '/dashboard', to: 'pages#dashboard'
  get '/perfil', to: 'pages#perfil'
  get '/colecao', to: 'pages#colecao'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skin.rb
class Skin < ApplicationRecord
  belongs_to :chroma

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :modification, presence: true

  validates :chroma, presence: false
end

app/controllers/skins_controller.rb
class SkinsController < ApplicationController
  before_action :set_skin, only: [:show, :edit, :update, :destroy]

  # GET /skins
  # GET /skins.json
  def index
    @skins = Skin.all
  end

  # GET /skins/1
  # GET /skins/1.json
  def show
  end

  # GET /skins/new
  def new
    @skin = Skin.new
  end

  # GET /skins/1/edit
  def edit
  end

  # POST /skins
  # POST /skins.json
  def create
    @skin = Skin.new(skin_params)

    respond_to do |format|
      if @skin.save
        format.html { redirect_to @skin, notice: 'Skin was successfully created.' }
        format.json { render :show, status: :created, location: @skin }
      else
        format.html { render :new }
        format.json { render json: @skin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skins/1
  # PATCH/PUT /skins/1.json
  def update
    respond_to do |format|
      if @skin.update(skin_params)
        format.html { redirect_to @skin, notice: 'Skin was successfully updated.' }
        format.json { render :show, status: :ok, location: @skin }
      else
        format.html { render :edit }
        format.json { render json: @skin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skins/1
  # DELETE /skins/1.json
  def destroy
    @skin.destroy
    respond_to do |format|
      format.html { redirect_to skins_url, notice: 'Skin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skin
      @skin = Skin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skin_params
      params.require(:skin).permit(:name, :price, :description, :modification, :chroma_id)
    end
end

app/helpers/skins_helper.rb
module SkinsHelper
end

app/views/skins/_form.html.erb
<%= form_with(model: skin, local: true) do |form| %>
  <% if skin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skin.errors.count, "error") %> prohibited this skin from being saved:</h2>

      <ul>
      <% skin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :modification %>
    <%= form.text_field :modification %>
  </div>

  <div class="field">
    <%= form.label :chroma_id %>
    <%= form.text_field :chroma_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skins/edit.html.erb
<h1>Editing Skin</h1>

<%= render 'form', skin: @skin %>

<%= link_to 'Show', @skin %> |
<%= link_to 'Back', skins_path %>

app/views/skins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Modification</th>
      <th>Chroma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skins.each do |skin| %>
      <tr>
        <td><%= skin.name %></td>
        <td><%= skin.price %></td>
        <td><%= skin.description %></td>
        <td><%= skin.modification %></td>
        <td><%= skin.chroma %></td>
        <td><%= link_to 'Show', skin %></td>
        <td><%= link_to 'Edit', edit_skin_path(skin) %></td>
        <td><%= link_to 'Destroy', skin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skin', new_skin_path %>

app/views/skins/new.html.erb
<h1>New Skin</h1>

<%= render 'form', skin: @skin %>

<%= link_to 'Back', skins_path %>

app/views/skins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skin.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @skin.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skin.description %>
</p>

<p>
  <strong>Modification:</strong>
  <%= @skin.modification %>
</p>

<p>
  <strong>Chroma:</strong>
  <%= @skin.chroma %>
</p>

<%= link_to 'Edit', edit_skin_path(@skin) %> |
<%= link_to 'Back', skins_path %>