config/routes.rb
Rails.application.routes.draw do
  resources :notices
  devise_for :users
  resources :users
  resources :stores
  resources :packages
  resources :champions
  resources :skins
  resources :chromas

  get '/dashboard', to: 'pages#dashboard'
  get '/perfil', to: 'pages#perfil'
  get '/colecao', to: 'pages#colecao'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/champion.rb
class Champion < ApplicationRecord
  belongs_to :skin

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true

  validates :skin, presence: false
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
  end

  # GET /champions/1/edit
  def edit
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update
    respond_to do |format|
      if @champion.update(champion_params)
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion.destroy
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def champion_params
      params.require(:champion).permit(:name, :price, :description, :skin_id)
    end
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/views/champions/_form.html.erb
<%= form_with(model: champion, local: true) do |form| %>
  <% if champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% champion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :skin_id %>
    <%= form.text_field :skin_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Skin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= champion.name %></td>
        <td><%= champion.price %></td>
        <td><%= champion.description %></td>
        <td><%= champion.skin %></td>
        <td><%= link_to 'Show', champion %></td>
        <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
        <td><%= link_to 'Destroy', champion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion', new_champion_path %>

app/views/champions/new.html.erb
<h1>New Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @champion.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @champion.description %>
</p>

<p>
  <strong>Skin:</strong>
  <%= @champion.skin %>
</p>

<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', champions_path %>